export const titleColorMap: Record<string, string> = {
  "AVIAR VALVE ASSEMBLY": "blue",
  "BLOW-OFF VALVE": "burlywood",
  "BREAK PRESSURE CHAMBER": "orange",
  "DISTRIBUTION PIPELINE": "",
  "END CAP": "black",
  "Fire Hydrant": "red",
  "GATE VALVE": "coral",
  "GROUND RESERVIOR": "green",
  "PVC BEND": "bisque",
  "REDUCER": "indianred",
  "SADDLE CLAMP": "yellow",
  "TEE": "aqua",
  "TRANSMISSION PIPELINE": ""
}

export const sizeColorMap: Record<string, string> = {
  "250mm x 200mm": "",
  "250mm x 50mm": "",
  "200mm x 150mm": "",
  "200mm x 100mm": "",
  "200mm x 75mm": "",
  "200mm x 50mm": "",
  "150mm x 250mm": "",
  "150mm x 100mm": "",
  "150mm x 75mm": "",
  "100mm x 75mm": "",
  "100mm x 50mm": "",
  "75mm x 50mm": "",
  "300mm": "darkslategray",
  "250mm": "green",
  "200mm": "lime",
  "150mm": "darkturquoise",
  "100mm": "steelblue",
  "75mm": "blue",
  "50mm": "aqua",
};
